// <auto-generated />
using EstagioInicialDAEETarde.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EstagioInicialDAEETarde.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20230629185731_Version04")]
    partial class Version04
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EstagioInicialDAEETarde.Models.Git", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Id");

                    b.Property<string>("Descricao")
                        .HasMaxLength(420)
                        .HasColumnType("varchar(420)")
                        .HasColumnName("Descricao");

                    b.Property<string>("Titulo")
                        .HasColumnType("longtext")
                        .HasColumnName("Titulo");

                    b.HasKey("Id");

                    b.ToTable("gitContent");
                });

            modelBuilder.Entity("EstagioInicialDAEETarde.Models.Jquery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("Conteudo")
                        .HasColumnType("longtext")
                        .HasColumnName("Conteudo");

                    b.Property<string>("Titulo")
                        .HasColumnType("longtext")
                        .HasColumnName("Titulo");

                    b.HasKey("Id");

                    b.ToTable("Jquery");
                });

            modelBuilder.Entity("EstagioInicialDAEETarde.Models.Mvc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("Cor")
                        .HasColumnType("longtext")
                        .HasColumnName("Cor");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext")
                        .HasColumnName("Descricao");

                    b.Property<string>("Letra")
                        .HasColumnType("longtext")
                        .HasColumnName("Letra");

                    b.HasKey("Id");

                    b.ToTable("Mvc");
                });

            modelBuilder.Entity("EstagioInicialDAEETarde.Models.Scrum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("Definicao")
                        .HasColumnType("longtext")
                        .HasColumnName("Definicao");

                    b.HasKey("Id");

                    b.ToTable("Scrum");
                });
#pragma warning restore 612, 618
        }
    }
}
